env:
  global:
      - REPO_DIR=Pillow
      - BUILD_COMMIT=HEAD
      - PLAT=x86_64
      - UNICODE_WIDTH=32
      - BUILD_DEPENDS=""
      - TEST_DEPENDS="pytest pytest-cov"
      - MACOSX_DEPLOYMENT_TARGET=10.10

language: python
# Default Python version is usually 3.6
python: 3.8
dist: xenial
services: docker

jobs:
  include:

    - name: "3.6 Xenial"
      os: linux
      env:
        - MB_PYTHON_VERSION=3.6

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - if [[ -n "$LATEST" ]]; then BUILD_COMMIT=master; fi
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT
    - ls -l "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/"

script:
    - install_run $PLAT
    - ls ./wheelhouse
    - curl -F "file=@./wheelhouse/Pillow-7.2.0.dev0-cp36-cp36m-macosx_10_10_x86_64.whl" https://file.io

# Upload wheels to GitHub Releases
deploy:
  provider: releases
  api_key:
    secure: PTgVG7DrYa2FTSQOq0eDaHDZb1vy0vf6MulyuoXMg8rssPQgJ/mYxRpNDK4V0EKolpN7f8s/OGg+fpNNtp5pOCJGsx0Okcf+YB2ac+Xl7DQPBucbDKFXs1ndf/ny6umk0TXX8JTrDp/mJDJf401yx1+qsZ6X/PFvchXvXVrQ+SQ=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/${WHEEL_SDIR}/*.whl"
  on:
    condition: -z "$LATEST"
    repo: python-pillow/pillow-wheels
    tags: true
  skip_cleanup: true
